services:
  itmo_chatbot_copy:  # Измененное имя сервиса
    container_name: itmo_chatbot_copy
    build: .
    ports:
      - "8081:8080"  # Пробросим на другой порт, чтобы не конфликтовало с оригиналом
    env_file:
      - .env
    volumes:
      - /app
    restart: always